import { useEffect } from 'react'
import type { Article } from '../api'

interface Citation {
  title: string
  url: string
}

interface Props {
  article: Article
  loading: boolean
  onClose: () => void
  onToggleStar: () => void
  onPrev: () => void
  onNext: () => void
  hasPrev: boolean
  hasNext: boolean
}

function fullDate(iso: string | null): string {
  if (!iso) return ''
  return new Date(iso).toLocaleDateString(undefined, {
    year: 'numeric',
    month: 'long',
    day: 'numeric',
  })
}

export function ArticleReader({
  article,
  loading,
  onClose,
  onToggleStar,
  onPrev,
  onNext,
  hasPrev,
  hasNext,
}: Props) {
  useEffect(() => {
    const handler = (e: KeyboardEvent) => {
      if (e.key === 'Escape') onClose()
      else if (e.key === 'ArrowLeft' && hasPrev) onPrev()
      else if (e.key === 'ArrowRight' && hasNext) onNext()
    }
    window.addEventListener('keydown', handler)
    return () => window.removeEventListener('keydown', handler)
  }, [onClose, onPrev, onNext, hasPrev, hasNext])

  const citations: Citation[] = article.citations_json ? JSON.parse(article.citations_json) : []

  return (
    <div className="reader-overlay">
      <div className="reader-bar">
        <div className="reader-bar__left">
          <button className="icon-btn" onClick={onClose} title="Close (Esc)">
            ←
          </button>
          <span className="reader-source">{article.source_title}</span>
        </div>
        <div className="reader-bar__right">
          <button
            className={`icon-btn ${article.is_starred ? 'active' : ''}`}
            onClick={onToggleStar}
            title="Star"
          >
            ★
          </button>
          {article.url && (
            <a
              className="icon-btn"
              href={article.url}
              target="_blank"
              rel="noreferrer"
              title="Open original"
            >
              ↗
            </a>
          )}
        </div>
      </div>

      {hasPrev && (
        <button
          className="reader-nav reader-nav--prev"
          onClick={onPrev}
          title="Previous article (←)"
        >
          ‹
        </button>
      )}
      {hasNext && (
        <button
          className="reader-nav reader-nav--next"
          onClick={onNext}
          title="Next article (→)"
        >
          ›
        </button>
      )}

      <div className="reader-scroll">
        <article className="reader-article">
          {article.origin === 'llm' && (
            <div className="reader-article__badges">
              <span className="badge badge--generated">Generated by Claude</span>
            </div>
          )}
          <h1 className="reader-article__title">{article.title}</h1>
          <div className="reader-article__meta">
            {article.author && <>{article.author} · </>}
            {fullDate(article.published_at)}
            {article.url && (
              <>
                {' · '}
                <a href={article.url} target="_blank" rel="noreferrer">
                  original source
                </a>
              </>
            )}
          </div>

          {loading ? (
            <div className="reader-skeleton">
              <div className="reader-skeleton__line" style={{ width: '95%' }} />
              <div className="reader-skeleton__line" style={{ width: '88%' }} />
              <div className="reader-skeleton__line" style={{ width: '92%' }} />
              <div className="reader-skeleton__line" style={{ width: '60%' }} />
            </div>
          ) : (
            <div
              className="reader-body"
              dangerouslySetInnerHTML={{
                __html: article.content_html || `<p>${article.excerpt}</p>`,
              }}
            />
          )}

          {citations.length > 0 && (
            <div className="reader-sources">
              <div className="reader-sources__label">Sources</div>
              {citations.map((c, i) => (
                <a key={i} className="reader-sources__item" href={c.url} target="_blank" rel="noreferrer">
                  {c.title}
                </a>
              ))}
            </div>
          )}
        </article>
      </div>
    </div>
  )
}
